name: Run update monitoring script

on:
  schedule:
    # daily, 4 AM UTC
    - cron:  '0 4 * * *'

jobs:
  activity-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master

      - name: Set GIT
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"

      - name: System & package dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
          Rscript -e "install.packages(c('rvest', 'gh', 'data.table'))"

      - name: Run Rscript
        env:
          BUGZILLA_USER: ${{ secrets.BUGZILLA_USER }}
          BUGZILLA_PASSWORD: ${{ secrets.BUGZILLA_PASSWORD }}
        run: Rscript update.R

      - name: Get Date
        id: date
        run: echo "::set-output name=date::$(TZ=UTC date +%Y-%m-%d %H-%M-%S)"

      - name: Commit new data
        run: |
          git add --all
          git commit -m "New data collected at ${{ steps.date.outputs.date }}" || echo "No updates to archive since last run"


      - name: Push data
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'master'
